/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: example.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "example.pb-c.h"
void   simple_message__init
                     (SimpleMessage         *message)
{
  static const SimpleMessage init_value = SIMPLE_MESSAGE__INIT;
  *message = init_value;
}
size_t simple_message__get_packed_size
                     (const SimpleMessage *message)
{
  assert(message->base.descriptor == &simple_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simple_message__pack
                     (const SimpleMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simple_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simple_message__pack_to_buffer
                     (const SimpleMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simple_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SimpleMessage *
       simple_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SimpleMessage *)
     protobuf_c_message_unpack (&simple_message__descriptor,
                                allocator, len, data);
}
void   simple_message__free_unpacked
                     (SimpleMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simple_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const int32_t simple_message__int_number__default_value = 10;
static const ProtobufCFieldDescriptor simple_message__field_descriptors[4] =
{
  {
    "str_value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SimpleMessage, str_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_number",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SimpleMessage, has_int_number),
    offsetof(SimpleMessage, int_number),
    NULL,
    &simple_message__int_number__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_array",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SimpleMessage, n_float_array),
    offsetof(SimpleMessage, float_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enum_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SimpleMessage, has_enum_value),
    offsetof(SimpleMessage, enum_value),
    &enum_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simple_message__field_indices_by_name[] = {
  3,   /* field[3] = enum_value */
  2,   /* field[2] = float_array */
  1,   /* field[1] = int_number */
  0,   /* field[0] = str_value */
};
static const ProtobufCIntRange simple_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor simple_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Simple_message",
  "SimpleMessage",
  "SimpleMessage",
  "",
  sizeof(SimpleMessage),
  4,
  simple_message__field_descriptors,
  simple_message__field_indices_by_name,
  1,  simple_message__number_ranges,
  (ProtobufCMessageInit) simple_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue enum_type__enum_values_by_number[2] =
{
  { "ENUM_ONE", "ENUM_TYPE__ENUM_ONE", 0 },
  { "ENUM_TWO", "ENUM_TYPE__ENUM_TWO", 1 },
};
static const ProtobufCIntRange enum_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex enum_type__enum_values_by_name[2] =
{
  { "ENUM_ONE", 0 },
  { "ENUM_TWO", 1 },
};
const ProtobufCEnumDescriptor enum_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EnumType",
  "EnumType",
  "EnumType",
  "",
  2,
  enum_type__enum_values_by_number,
  2,
  enum_type__enum_values_by_name,
  1,
  enum_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
